### ISSUE TITLE
Problème d'ajout de liste d'objet dans un objet mongo

### ISSUE THREAD

**Issue by Quentin61** [Quentin61/Ember-tds#2]
J'ai un problème concernant l'ajout de story dans un projet, je n'ai pas trouvé de méthode qui permet à partir de l'id d'un projet, et d'un objet story d'ajouter un tableau de story dans l'objet projet. @Jcheron
```
actions:
    {
      new(story, id)
      {
        let self = this;
        let project = this.get('store').findRecord('developer', id.project_id);
        let arrayStories = project.get('story');
        let finalArray = arrayStories.concat(story);
      }
    }
```

**Comment by jcheron** [comment]
Difficile de vous aider...
Vous ne mettez même pas la route concernée, le template associé...

**Comment by Quentin61** [comment]
la route concernée est la route `/new/:project_id` dans le router.js et le template associé est new.hbs dans le dossier story

**Comment by jcheron** [comment]
Pour ajouter dans un array, utiliser `pushObject`:
```javascript
actions:
    {
      new(story, id)
      {
        let self = this;
        let project = this.get('store').findRecord('developer', id.project_id);
        project.get(‘stories’).pushObject(story);

      }
    }
```
Ce qui est bizarre, c'est de recharger un project, vous n'auriez pas pu passer le projet existant à l'action new ?
